;/*FB_PKG_DELIM*/

__d("CometVisualCompletionConstants",[],(function(a,b,c,d,e,f){"use strict";a="data-visualcompletion";b="HeroTracing";c="InteractionTracing";d="ignore";e="ignore-dynamic";var g="ignore-late-mutation",h="loading-state",i="media-vc-image",j="css-img";f.ATTRIBUTE_NAME=a;f.HERO_TRACING_HOLD=b;f.INTERACTION_TRACING_HOLD=c;f.IGNORE=d;f.IGNORE_DYNAMIC=e;f.IGNORE_LATE_MUTATION=g;f.LOADING_STATE=h;f.MEDIA_VC_IMAGE=i;f.CSS_IMG=j}),66);
__d("CometVisualCompletionAttributes",["CometVisualCompletionConstants"],(function(a,b,c,d,e,f,g){"use strict";b={CSS_IMG:(a={},a[d("CometVisualCompletionConstants").ATTRIBUTE_NAME]=d("CometVisualCompletionConstants").CSS_IMG,a),IGNORE:(b={},b[d("CometVisualCompletionConstants").ATTRIBUTE_NAME]=d("CometVisualCompletionConstants").IGNORE,b),IGNORE_DYNAMIC:(c={},c[d("CometVisualCompletionConstants").ATTRIBUTE_NAME]=d("CometVisualCompletionConstants").IGNORE_DYNAMIC,c),IGNORE_LATE_MUTATION:(e={},e[d("CometVisualCompletionConstants").ATTRIBUTE_NAME]=d("CometVisualCompletionConstants").IGNORE_LATE_MUTATION,e),LOADING_STATE:(f={},f[d("CometVisualCompletionConstants").ATTRIBUTE_NAME]=d("CometVisualCompletionConstants").LOADING_STATE,f),MEDIA_VC_IMAGE:(a={},a[d("CometVisualCompletionConstants").ATTRIBUTE_NAME]=d("CometVisualCompletionConstants").MEDIA_VC_IMAGE,a)};g["default"]=b}),98);
__d("IntlCLDRNumberType03",["IntlVariations"],(function(a,b,c,d,e,f,g){"use strict";a={getVariation:function(a){if(a===0||a===1)return c("IntlVariations").NUMBER_ONE;else return c("IntlVariations").NUMBER_OTHER}};b=a;g["default"]=b}),98);
__d("IntlCLDRNumberType04",["IntlVariations"],(function(a,b,c,d,e,f,g){"use strict";a={getVariation:function(a){if(a>=0&&a<=1)return c("IntlVariations").NUMBER_ONE;else return c("IntlVariations").NUMBER_OTHER}};b=a;g["default"]=b}),98);
__d("IntlCLDRNumberType09",["IntlVariations"],(function(a,b,c,d,e,f,g){"use strict";a={getVariation:function(a){if(a===1)return c("IntlVariations").NUMBER_ONE;else return c("IntlVariations").NUMBER_OTHER}};b=a;g["default"]=b}),98);
__d("TrustedTypesIEFixDOMPolicy",["TrustedTypes"],(function(a,b,c,d,e,f,g){"use strict";a={createHTML:function(a){return a}};b=c("TrustedTypes").createPolicy("dom-ie-fix",a);d=b;g["default"]=d}),98);
__d("XPagesManagerPageQualityController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/{page_token}/quality/",{business_id:{type:"Int"},page_token:{type:"String",required:!0},focused_post_id:{type:"FBID"},focused_co_content_id:{type:"FBID"},referrer:{type:"Enum",enumType:1},xi_initial_modal:{type:"Enum",enumType:1},is_matched_content:{type:"Bool",defaultValue:!1}})}),null);
__d("XPagesManagerPublishingToolsController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/{page_token}/publishing_tools/",{privacy_mutation_token:{type:"String"},business_id:{type:"Int"},page_token:{type:"String",required:!0},current_page:{type:"Int"},section:{type:"String"},source:{type:"Enum",enumType:1},sourceID:{type:"String"},refSource:{type:"Enum",enumType:1},initial_action_data:{type:"StringToStringMap"},initial_data:{type:"StringToStringMap"},modal:{type:"Enum",enumType:1}})}),null);
__d("XPagesManagerSettingsController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/{page_token}/settings/",{business_id:{type:"Int"},page_token:{type:"String",required:!0},edited:{type:"String"},section:{type:"String"},tab:{type:"String"},change_admin_action:{type:"String"},change_admin_uid:{type:"Int"},tbid:{type:"Int"},fid:{type:"Int"},item_id:{type:"Int"},ref:{type:"String"},shimmed_in_item:{type:"Bool",defaultValue:!1},q:{type:"String"},promote_plugin_tab:{type:"Enum",enumType:1},active_section:{type:"String"},on_load_actions:{type:"StringVector"},partner_id:{type:"Int"},enable:{type:"Enum",enumType:1},creator_request_id:{type:"Int"},show_cc_dialog:{type:"Bool",defaultValue:!1},chat_plugin_step:{type:"Int",defaultValue:0},country_code:{type:"Enum",enumType:1},show_sync_dialog:{type:"Bool",defaultValue:!1},job_manager_requester_id:{type:"Int"}})}),null);
__d("XVideoPermalinkController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/{vanity}/videos/{?set_token}/{video_id}/{?story_token}/{?*extra_junk}/",{extid:{type:"String"},mibextid:{type:"String"},comment_id:{type:"IntOrPFBID"},photo_id:{type:"Int"},set_token:{type:"String"},type:{type:"Enum",defaultValue:3,enumType:0},link_share:{type:"String"},subject:{type:"Int"},object_id:{type:"Int"},opaque_cursor:{type:"String"},legacy_user_id:{type:"IntOrPFBID"},legacy_photo_id:{type:"Int"},video_id:{type:"Int"},notif_t:{type:"String"},is_notification_preview:{type:"Bool",defaultValue:!1},force_theater:{type:"Bool",defaultValue:!1},story_token:{type:"String"},reply_comment_id:{type:"IntOrPFBID"},comment_tracking:{type:"String"},vanity:{type:"String"},__tn__:{type:"String"},privacy_mutation_token:{type:"String"},t:{type:"Int"},flite:{type:"String"},__so__:{type:"Enum",enumType:1},__rv__:{type:"Enum",enumType:1},redirect:{type:"Bool",defaultValue:!0},depth:{type:"Int"},extra_junk:{type:"String"},comments_modal:{type:"Bool",defaultValue:!1},idorvanity:{type:"String"}})}),null);
__d("XWebGraphQLMutationController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/webgraphql/mutation/",{query_id:{type:"FBID"},variables:{type:"String"},doc_id:{type:"FBID"},legacy_response_format:{type:"Bool",defaultValue:!1}})}),null);
__d("flipObject",[],(function(a,b,c,d,e,f){"use strict";function a(a){return Object.entries(a).reduce(function(b,c){var d=c[0];c=c[1];Object.prototype.hasOwnProperty.call(a,d)&&typeof c!=="object"&&typeof c!=="function"&&c!=null&&(b[String(c)]=d);return b},{})}f["default"]=a}),66);